import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="/richtexteditor/rte_theme_default.css" />  
    <script type="text/javascript" src="/richtexteditor/rte.js"></script>  
    <script type="text/javascript" src='/richtexteditor/plugins/all_plugins.js'></script> 
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
